Task on arrays
IgorSusolkin/IgorSusolkin.github.io pull request #2
Opened 2017-03-30 10:13 UTC by IgorSusolkin

2017-04-02 07:26 UTC, NikitaSedyx requested changes

2017-04-02 07:26 UTC, NikitaSedyx commented on task on arrays/script.js
> +  return typeof obj ==="object" &&
imo `typeof obj ==="object"` is not required
in additional code styles is bad. for your case you could use
```
return (typeof obj ==="object" &&
  Object.prototype.toString.call(obj) === "[object Array]");
```

2017-04-02 07:26 UTC, NikitaSedyx commented on task on arrays/script.js
> +function range(a, /*необязательный*/ b ,
`b,`

2017-04-02 07:26 UTC, NikitaSedyx commented on task on arrays/script.js
> +  /*необязательный*/ c) {
it's not place for comments, doc string should be used

2017-04-02 07:26 UTC, NikitaSedyx commented on task on arrays/script.js
> +    else array.length = 0;
initial array is mutated, -1
please use brackets for if else, it's better to read

2017-04-02 07:26 UTC, NikitaSedyx commented on task on arrays/script.js
> +    step = c || 1;
you could call c argument as step and don't define new variable

2017-04-02 07:26 UTC, NikitaSedyx commented on task on arrays/script.js
> +function compact(array) {
nit: please put empty line between functions, for readability

2017-04-04 06:49 UTC, NikitaSedyx approved these changes
looks like it works, please fix comments

2017-04-04 06:49 UTC, NikitaSedyx commented on task on arrays/script.js
> +  if (!b) {
it won't work when b is 0
it's better to use strong condition in such cases

2017-04-04 06:49 UTC, NikitaSedyx commented on task on arrays/script.js
> +  return (!!obj && obj.constructor === Array);
nit: brackets are not required,  `obj` will work without type converting

2017-04-04 08:17 UTC, IgorSusolkin commented on task on arrays/script.js
> +  return (!!obj && obj.constructor === Array);
obj dont work without type converting
console.log(isArray2({}));//false
console.log(isArray2([]));//true
console.log(isArray2(""));//""
console.log(isArray2("5"));//false
console.log(isArray2(5));//false
console.log(isArray2(null));//null
console.log(isArray2(undefined));//underfined
console.log(typeof(isArray2({})));//boolean
console.log(typeof(isArray2([])));//boolean
console.log(typeof(isArray2("")));//string
console.log(typeof(isArray2("5")));//boolean
console.log(typeof(isArray2(5)));//boolean
console.log(typeof(isArray2(null)));//object
console.log(typeof(isArray2(undefined)));//undefined

2017-04-06 10:38 UTC, merged